spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost/wsc_admin?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&useTimezone=true&allowPublicKeyRetrieval=true
    type: com.alibaba.druid.pool.DruidDataSource
mybatis-plus:
  type-handlers-package: com.zhenmei.wsc.demo.handler

server:
  port: 8777
  servlet:
    context-path: /

