spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost/wsc_admin?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&useTimezone=true&allowPublicKeyRetrieval=true&socketTimeout=60000
    type: com.alibaba.druid.pool.DruidDataSource
  task:
    execution:
      pool:
        core-size: 10
        max-size: 50
server:
  port: 8777
  servlet:
    context-path: /

