spring:
  h2:
    console:
      enabled: true
      path: /h2-database
  sql:
    init:
      schema-locations: classpath:db/schema-h2.sql
      data-locations: classpath:db/data-h2.sql
  jackson:
    default-property-inclusion: non_null

wsc:
  ds1:
    driver-class-name: org.h2.Driver
    username: root
    password:
    url: jdbc:h2:mem:testdb;MODE=MYSQL;CASE_INSENSITIVE_IDENTIFIERS=FALSE

server:
  port: 8888
  servlet:
    context-path: /

