spring:
  datasource:
    username: root
    password: Mm5590026
    url: jdbc:mysql://150.158.186.188/mamba_view?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT&useTimezone=true
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    default-property-inclusion: non_null


server:
  port: 2408
  servlet:
    context-path: /

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations: classpath*:com/zhenmei/mybatis/generate/mapper/*.xml  #支持逗号分割多个路劲


#自定义数据源
custom:
  datasource:
    username: root
    password: Mm5590026
    url: jdbc:mysql://150.158.186.188/mamba_view?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&useTimezone=true
    type: com.alibaba.druid.pool.DruidDataSource
