spring:
  datasource:
    username: root
    password: Mm5590026
    url: jdbc:mysql://150.158.186.188/mamba_view?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT&useTimezone=true
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    default-property-inclusion: non_null

custom:
  datasource:
    username: root
    password: Mm5590026
    url: jdbc:mysql://150.158.186.188/mamba_view?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&useTimezone=true
    type: com.alibaba.druid.pool.DruidDataSource

server:
  port: 2408
  servlet:
    context-path: /