spring:
  h2:
    console:
      enabled: true
      path: /h2-database
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql
    username: root
    password: test
    url: jdbc:h2:mem:test
  jackson:
    default-property-inclusion: non_null


server:
  port: 2408
  servlet:
    context-path: /

